name: locker_mobile
description: "A mobile application for the Locker project, featuring food ordering and maps."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  mobile_scanner: ^6.0.0
  get_it: ^9.2.1
  mapbox_maps_flutter: ^2.25.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.2.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FB923C"
  adaptive_icon_foreground: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
