// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrWwwPso2mWurMB3dNhV5skWSFtr-SN3M',
    appId: '1:387468164943:web:0515db576439df3770cf3a',
    messagingSenderId: '387468164943',
    projectId: 'locker-c469d',
    authDomain: 'locker-c469d.firebaseapp.com',
    storageBucket: 'locker-c469d.firebasestorage.app',
    measurementId: 'G-KG182C1CB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLhTwVsLGKk-3SkTqHvnnwPzdpIbxdYg',
    appId: '1:387468164943:android:c60d0260f55d271c70cf3a',
    messagingSenderId: '387468164943',
    projectId: 'locker-c469d',
    storageBucket: 'locker-c469d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL67bB2Kya7FZw4r3PY4NwbPNHKOFMKgQ',
    appId: '1:387468164943:ios:a7a0a82d1ad54c0c70cf3a',
    messagingSenderId: '387468164943',
    projectId: 'locker-c469d',
    storageBucket: 'locker-c469d.firebasestorage.app',
    iosBundleId: 'com.example.lockerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL67bB2Kya7FZw4r3PY4NwbPNHKOFMKgQ',
    appId: '1:387468164943:ios:a7a0a82d1ad54c0c70cf3a',
    messagingSenderId: '387468164943',
    projectId: 'locker-c469d',
    storageBucket: 'locker-c469d.firebasestorage.app',
    iosBundleId: 'com.example.lockerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrWwwPso2mWurMB3dNhV5skWSFtr-SN3M',
    appId: '1:387468164943:web:f02cedefedaa13f470cf3a',
    messagingSenderId: '387468164943',
    projectId: 'locker-c469d',
    authDomain: 'locker-c469d.firebaseapp.com',
    storageBucket: 'locker-c469d.firebasestorage.app',
    measurementId: 'G-N5NTPX98SP',
  );
}
